// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC9ruEC34iFUPLJXLRHILlIpj--a4UIX9g",

      authDomain: "slutproject-flutterv4.firebaseapp.com",

      projectId: "slutproject-flutterv4",

      storageBucket: "slutproject-flutterv4.appspot.com",

      messagingSenderId: "364664568224",

      appId: "1:364664568224:web:061c98cb6b7ed7b7af4cc5"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyKGoiCG3yXUsMNQxEk1CcsIIB74auUE',
    appId: '1:929020475247:android:e2dec29f61b3e2c7325a9a',
    messagingSenderId: '929020475247',
    projectId: 'slutproject-flutter',
    databaseURL: 'https://slutproject-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slutproject-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKh48F2vuZcwIgLTM-jKKwvM_sGcaJB8',
    appId: '1:929020475247:ios:1adf5aa46561dfcf325a9a',
    messagingSenderId: '929020475247',
    projectId: 'slutproject-flutter',
    databaseURL: 'https://slutproject-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slutproject-flutter.appspot.com',
    iosBundleId: 'com.example.slutprojectV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKh48F2vuZcwIgLTM-jKKwvM_sGcaJB8',
    appId: '1:929020475247:ios:4efbf5b0be43791c325a9a',
    messagingSenderId: '929020475247',
    projectId: 'slutproject-flutter',
    databaseURL: 'https://slutproject-flutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'slutproject-flutter.appspot.com',
    iosBundleId: 'com.example.slutprojectV3.RunnerTests',
  );
}
